version: "3"

services:

  app:
    container_name: twill
    restart: unless-stopped
    image: hub.devfactory.ch/devfactory/docker/dev/laravel-8.2:latest
    ports:
      - '${VITE_PORT:-5174}:${VITE_PORT:-5174}'
    networks:
      - mysql
      - mariadb
      - redis
      - traefik
      - mailpit
    environment:
      - DB_HOST=mariadb
      - DB_USERNAME=root
      - DB_PASSWORD=
      - LOG_CHANNEL=stderr
    volumes:
      - ./:/app
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.twill.rule=Host(`twill.localhost`)"
      - "traefik.http.routers.twill.entrypoints=web"
      - "traefik.http.services.twill.loadbalancer.server.port=8000"
      - "--entrypoints.web.address=:8000"

networks:
  mysql:
    external: true
  mariadb:
    external: true
  redis:
    external: true
  mailpit:
    external: true
  traefik:
    external: true
